<a href="https://colab.research.google.com/github/mmartigani/RoadMapIA/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import time

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Ciudades_Visitadas_Latinoamerica_2023.csv")
df.head(5)

Ciudad       País  Población  Visitantes
0  Ciudad de México     México    9265833    21000000
1      Buenos Aires  Argentina    3059574    15000000
2    Río de Janeiro     Brasil    6748314    13000000
3              Lima       Perú    9756020     9000000
4            Bogotá   Colombia    7181663     8000000

In [4]:
df["Población"].mean()

np.float64(5863276.8)

In [5]:
np.round(df["Población"].mean())

np.float64(5863277.0)

In [6]:
np.min(df["Visitantes"])

3000000

In [7]:
np.max(df["Visitantes"])

21000000

In [9]:
mi_array = np.array( [1,2,3,4,5])
mi_array

array([1, 2, 3, 4, 5])

In [10]:
print(type(mi_array))

<class 'numpy.ndarray'>


In [11]:
lista_grande = list(range(1000000))
array_grande = np.array(lista_grande)

In [13]:
print(type(lista_grande))
print(type(array_grande))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
inicio_lista = time.time()
for i in lista_grande:
  i ** 2
fin_lista = time.time()
print(f" Tiempo lista:" ,fin_lista - inicio_lista)

 Tiempo lista: 0.0864262580871582


In [16]:
inicio_array = time.time()
array_grande **2
fin_array = time.time()
print(f" Tiempo array:" ,fin_array - inicio_array)

 Tiempo array: 0.00435328483581543


In [22]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [18]:
len(array)

3

In [19]:
array.shape

(3,)

In [21]:
array_2d = np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array_2d.shape

(2, 3)

In [24]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])

In [25]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
np.concatenate([a,b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [29]:
np.concatenate([a,b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
array_concatenado = np.concatenate([a,b], axis=0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
array_concatenado.shape

(4, 2)

In [33]:
array_reformado = array_concatenado.reshape(2,4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [35]:
array_multi = array_reformado * array_reformado
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [36]:
#calculo de la raiz cuadrada
raices = np.sqrt(array_multi)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [55]:
arrayid = np.array([1,2,3,4,5])

In [56]:
arrayid[0]

np.int64(1)

In [45]:
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [46]:
array2[0]

array([1, 2, 3])

In [47]:
array2[1][2]

np.int64(6)

In [48]:
arrayid[1:4]

[2, 3, 4]

In [49]:
array2[1,:]

array([4, 5, 6])

In [51]:
array2[1,1:3]

array([5, 6])

In [52]:
array2[:,1]

array([2, 5, 8])

In [53]:
array2[:2,:2]

array([[1, 2],
       [4, 5]])

In [57]:
arrayid > 3

array([False, False, False,  True,  True])

In [58]:
array2 %2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [59]:
array3=np.array([1,2,3,4,5,6,7,8,9])
array3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
array3.shape

(9,)

In [62]:
array_mod = array2.reshape(3,3)
array_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
array_vol = array_mod.transpose()
array_vol

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [65]:
array_fla = array_mod.flatten()
array_fla

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [67]:
b = np.array([[0],[10],[20],[30]])
b

array([[ 0],
       [10],
       [20],
       [30]])

In [68]:
suma = a + b
suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [69]:
c = np.array([1,2,3])
d = np.array([4,5,6,])

In [70]:
result = np.add(c,d)
result

array([5, 7, 9])

In [71]:
result = np.subtract(c,d)
result

array([-3, -3, -3])

In [72]:
result = np.multiply(c,d)
result

array([ 4, 10, 18])

In [73]:
result = np.divide(c,d)
result

array([0.25, 0.4 , 0.5 ])

In [74]:
result = np.exp(c)
result

array([ 2.71828183,  7.3890561 , 20.08553692])

In [75]:
result = np.log(c)
result

array([0.        , 0.69314718, 1.09861229])

In [76]:
result = np.log10(c)
result

array([0.        , 0.30103   , 0.47712125])

In [77]:
result = np.sqrt(c)
result

array([1.        , 1.41421356, 1.73205081])

In [78]:
array4 = np.array([1,2,np.nan,4,5])
array4

array([ 1.,  2., nan,  4.,  5.])

In [80]:
np.isnan(array4)

array([False, False,  True, False, False])

In [81]:
np.mean(array4)

np.float64(nan)

In [82]:
np.nanmean(array4)

np.float64(3.0)

In [83]:
array_con_ceros = np.where(np.isnan(array4),0,array4)
array_con_ceros

array([1., 2., 0., 4., 5.])

In [84]:
promedio = np.nanmean(array4)
array_promedio = np.where(np.isnan(array4),promedio,array4)
array_promedio

array([1., 2., 3., 4., 5.])

In [86]:
array_filtrado = array4[~np.isnan(array4)]
array_filtrado

array([1., 2., 4., 5.])

In [91]:
x=pd.read_csv("//content/drive/MyDrive/medallas.csv")
x.head(4)

Oro  Plata  Bronce  Total       Pais
0  NaN    1.0     2.0    3.0  Argentina
1  NaN    2.0     2.0    4.0    Armenia
2   17    7.0    22.0   46.0  Australia
3    1    1.0     5.0    7.0    Austria

In [93]:
aa = np.genfromtxt("/content/drive/MyDrive/medallas.csv", delimiter=",",filling_values=0,skip_header=1,dtype=int)
aa[:10]

array([[ 0,  1,  2,  3,  0],
       [ 0,  2,  2,  4,  0],
       [17,  7, 22, 46,  0],
       [ 1,  1,  5,  7,  0],
       [ 0,  3,  4,  7,  0],
       [ 2,  0,  0,  2,  0],
       [ 0,  1,  0,  1,  0],
       [ 1,  3,  3,  7,  0],
       [ 3,  1,  3,  7,  0],
       [ 1,  0,  0,  1,  0]])

In [94]:
ejemplo = np.array([[1,2,3],[4,5,6,]])

In [95]:
z=pd.read_csv("//content/drive/MyDrive/medallas.csv")

In [99]:
np.savetxt("ejemplo.csv",ejemplo, delimiter=",",fmt='%d')

In [101]:
df1 = pd.DataFrame({
    "imapres":[1,3,5],
    "pares":[2,4,6]
})
df1

imapres  pares
0        1      2
1        3      4
2        5      6

In [103]:
s = df1.values
s

array([[1, 2],
       [3, 4],
       [5, 6]])

In [104]:
s = df1.to_numpy()
s

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
np.sqrt(df1)

imapres     pares
0  1.000000  1.414214
1  1.732051  2.000000
2  2.236068  2.449490

In [107]:
df_desde_np = pd.DataFrame(s, columns=["col1", "col2"])
df_desde_np

col1  col2
0     1     2
1     3     4
2     5     6

In [108]:
h = pd.read_csv("/content/drive/MyDrive/datos_meteorologicos.csv")
h.head(3)

Fecha  Temperatura  Precipitación    Humedad
0  01/01/2010    17.440675      10.957482  52.384637
1  02/01/2010    25.759468       5.315628  30.633530
2  03/01/2010    20.138169      15.317706  41.496715

In [109]:
h.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


In [110]:
h.describe()

Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

In [112]:
temperatura = h["Temperatura"].to_numpy()
precipitacion = h["Precipitación"].to_numpy()
humedad = h["Humedad"].to_numpy()
temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
               nan, 37.30804318])

In [113]:
precipitacion

array([10.957482  ,  5.31562765, 15.31770609, ...,  4.61501177,
               nan,  7.33051023])

In [114]:
humedad

array([52.38463749, 30.63352983, 41.49671458, ..., 18.36284738,
               nan, 50.64621058])

In [115]:
t_nulo = np.isnan(temperatura)
t_nulo

array([False, False, False, ..., False,  True, False])

In [116]:
p_nulo = np.isnan(precipitacion)
p_nulo

array([False, False, False, ..., False,  True, False])

In [117]:
h_nulo = np.isnan(humedad)
h_nulo

array([False, False, False, ..., False,  True, False])

In [118]:
t_preomedio = np.nanmean(temperatura)
t_preomedio

np.float64(14.889295723531715)

In [119]:
p_preomedio = np.nanmean(precipitacion)
p_preomedio

np.float64(9.9016035987084)

In [120]:
h_preomedio = np.nanmean(humedad)
h_preomedio

np.float64(54.35906079674394)

In [121]:
temperatura[t_nulo] = t_preomedio
precipitacion[p_nulo] = p_preomedio
humedad[h_nulo] = h_preomedio
temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
       14.88929572, 37.30804318])

In [122]:
p_total = np.sum(precipitacion)
p_total

np.float64(50597.19438939993)

In [123]:
h_max = np.max(humedad)
h_max

np.float64(99.99658156071747)

In [124]:
caluroso = np.max(temperatura)
caluroso

np.float64(39.99820092713012)

In [125]:
registro_calor = np.where(temperatura == caluroso)[0][0]
registro_calor

np.int64(2749)

In [126]:
f_calurosa = h.iloc[registro_calor]["Fecha"]
f_calurosa

'12/07/2017'

In [130]:
f_fria = h.iloc[np.where(temperatura == np.min(temperatura))[0][0]]["Fecha"]
f_fria

'23/07/2020'

In [131]:
r = pd.DataFrame({"metrica":["temperatura promedio", "precipitacion total","humedad maxima","dias mas calurosos","dia mas frio"],
                  "valor":[t_preomedio,p_total,h_max,f_calurosa,f_fria]})
r.to_csv("resultados del analisis meteorologico.csv", index=False)