<a href="https://colab.research.google.com/github/mmartigani/RoadMapIA/blob/main/Tensores_Operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importamos tensorflow
import tensorflow as tf
tf.__version__

'2.18.0'

In [2]:
# El tensor representa una matriz
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
# El tensor representa un escalar
tf.constant(15)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [4]:
t = tf.constant([[1., 2.],[3., 4.]])
t.shape

TensorShape([2, 2])

In [5]:
t.dtype

tf.float32

In [6]:
# Definicion de un tensor que representa una matriz
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [7]:
# Acceso a la segunda fila del tensor
t[0,:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [8]:
# Acceso a la primera columna del tensor
t[:, 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [9]:
# Definicion de un tensor que representa una matriz
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t.shape

TensorShape([2, 3])

In [10]:
# Suma de un tensor y un escalar
print(t)
print(t + 10)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)


In [11]:
# Suma de dos tensores
print(t + t)

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


In [12]:
# Cuadrado de un tensor
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [13]:
# Creacion de dos tensores
t1 = tf.constant(1.0)
t2 = tf.constant(2)

In [14]:
print("Tipo t1:", t1.dtype)
print("Tipo t2:", t2.dtype)

Tipo t1: <dtype: 'float32'>
Tipo t2: <dtype: 'int32'>


In [15]:
try:
    t3 = t1 + t2
except Exception as e:
    print("Exception:", e)

Exception: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 


In [16]:
try:
    tf.constant([1, 2, 3]) + tf.constant([1.0, 2.0, 3.0])
except Exception as e:
    print("Exception:", e)

Exception: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 


In [18]:
t = tf.Variable([1.0, 2.0, 3.0])
t[0].assign(4.0)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([4., 2., 3.], dtype=float32)>

In [19]:
t = tf.Variable([1.0, 2.0, 3.0])
print("Tensor original:", t.value())

t[0].assign(2.0)
print("Tensor modificado:", t.value())

Tensor original: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Tensor modificado: tf.Tensor([2. 2. 3.], shape=(3,), dtype=float32)


In [20]:
tf.constant(b"hola mundo")

<tf.Tensor: shape=(), dtype=string, numpy=b'hola mundo'>

In [21]:
tf.constant("españa")

<tf.Tensor: shape=(), dtype=string, numpy=b'espa\xc3\xb1a'>

In [22]:
tf.constant(["hola", "mundo", "españa"])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'hola', b'mundo', b'espa\xc3\xb1a'], dtype=object)>